### Numpy Tutorials
NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python

What is an array
An array is a data structure that stores values of same data type. In Python, this is the main difference between arrays and lists. While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type

In [1]:
import numpy as np

In [3]:
a_list=[1,2,3,4,5,6,7]
arr=np.array(a_list)
print(arr)

[1 2 3 4 5 6 7]


In [4]:
type(arr)

numpy.ndarray

In [5]:
## Multinested array

a_list=[1,2,3,4,5]
b_list=[3,4,5,6,7]
c_list=[5,6,7,8,9]
arr2=np.array([a_list,b_list,c_list])
print(arr2)

[[1 2 3 4 5]
 [3 4 5 6 7]
 [5 6 7 8 9]]


In [7]:
## check the shape of the array
arr2.shape

(3, 5)

In [8]:
arr.shape

(7,)

### Indexing

In [9]:
arr

array([1, 2, 3, 4, 5, 6, 7])

In [10]:
arr[2:]

array([3, 4, 5, 6, 7])

In [11]:
arr[1:5:2]

array([2, 4])

In [12]:
arr[:4]

array([1, 2, 3, 4])

In [15]:
#2D array indexing
arr2

array([[1, 2, 3, 4, 5],
       [3, 4, 5, 6, 7],
       [5, 6, 7, 8, 9]])

In [16]:
arr2[:,:]

array([[1, 2, 3, 4, 5],
       [3, 4, 5, 6, 7],
       [5, 6, 7, 8, 9]])

In [17]:
arr2[0:2,2:4]

array([[3, 4],
       [5, 6]])

In [18]:
arr2[1:2,1:4]

array([[4, 5, 6]])

In [19]:
arr

array([1, 2, 3, 4, 5, 6, 7])

In [20]:
arr[4:]=100

In [21]:
arr

array([  1,   2,   3,   4, 100, 100, 100])

In [22]:
arr2

array([[1, 2, 3, 4, 5],
       [3, 4, 5, 6, 7],
       [5, 6, 7, 8, 9]])

In [24]:
arr2[0:2,1:4]=100

In [25]:
arr2

array([[  1, 100, 100, 100,   5],
       [  3, 100, 100, 100,   7],
       [  5,   6,   7,   8,   9]])

In [27]:
arr

array([  1,   2,   3,   4, 100, 100, 100])

In [26]:
### Some conditions very useful in Exploratory Data Analysis 

arr[arr<4]

array([1, 2, 3])

In [28]:
arr[arr<2]

array([1])

In [29]:
arr[arr>100]

array([], dtype=int32)

In [31]:
arr[arr>3]

array([  4, 100, 100, 100])

In [33]:
## Create arrays and reshape

arr3=np.arange(10)
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
arr3.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [40]:
arr3=np.arange(10).reshape(5,2)
arr3

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [41]:
arr3=np.arange(10).reshape(5,2)
arr4=np.arange(10).reshape(5,2)

In [42]:
arr3*arr4

array([[ 0,  1],
       [ 4,  9],
       [16, 25],
       [36, 49],
       [64, 81]])

In [47]:
arr5=np.arange(0,4).reshape(2,2)
arr6=np.arange(4,8).reshape(2,2)
arr5*arr6

array([[ 0,  5],
       [12, 21]])

In [45]:
print([arr5,arr6])

[array([[0, 1],
       [2, 3]]), array([[4, 5],
       [6, 7]])]


In [46]:
arr5*arr6

array([[ 0,  5],
       [12, 21]])

In [48]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [49]:
np.ones((2,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [52]:
## random distribution
np.random.rand(3,3)

array([[0.70071844, 0.90060275, 0.80359906],
       [0.13735685, 0.24411453, 0.92417136],
       [0.02906013, 0.75618841, 0.13002412]])

In [53]:
arr_ex=np.random.randn(4,4)
arr_ex

array([[ 0.74366676,  0.19495457, -0.60766075,  2.06812413],
       [-0.63187333, -1.01035305,  0.98954655,  0.20933149],
       [ 0.95960491,  1.00404272,  0.08376377,  0.50013957],
       [-2.03505777,  0.21515904, -1.76067353,  0.73631263]])

In [55]:
np.random.randint(0,100,8).reshape(4,2)

array([[63, 92],
       [44, 53],
       [35, 49],
       [36, 40]])